CREATE USER dashboard WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '123456';
	
CREATE DATABASE dashboard
    WITH 
    OWNER = dashboard
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
\connect dashboard;
	
CREATE SCHEMA dashboard
    AUTHORIZATION dashboard;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
