apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-prod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data_db_prod"
