apiVersion: apps/v1
kind: Deployment
metadata:
  name: areas-backend-deployment
  namespace: prod
  labels:
    app: areas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: areas-backend
  template:
    metadata:
      labels:
        app: areas-backend
      namespace: prod
    spec:
      containers:
      - name: areas-backend
        image: fredkor/api-areas-backend:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: 8080tcp
            protocol: TCP
        resources:
          requests:
            cpu: "250m"
            memory: "400Mi"
          limits:
            cpu: "600m"
            memory: "500Mi"
        env:
        - name: FLASK_ENV
          value: development
        - name: CONTEXT_PATH
          value: apidashboard
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: POSTGRES_USER
        - name: USER_PWS
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: POSTGRES_PASSWORD
        - name: DB_HOST
          value: postgres-db-service
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: POSTGRES_DB
        - name: LOG_LEVEL
          value: debug
        - name: VERSION
          value: 1.0.0
