apiVersion: v1
kind: ConfigMap
metadata:
  name: areas-frontend-configmap
  namespace: prod
data:
  config.json: |
    {
      "API_URL": "http://areas.local.prod/apidashboard",
      "VERSION": "1.0.0"
    }
